#!/usr/bin/bash

set -e

name="chat"
base_name=$(basename $0)
dir_name=$(dirname $0)


if [[ -z "$(docker images -q $name)" ]]; then
    docker build -t $name $dir_name
fi

if [[ -z "$(docker ps -a --quiet -f name=$name)" ]]; then
    docker run -d -t --name $name -v $dir_name/..:/root/$name $name
elif [[ -z "$(docker ps -a --quiet -f name=$name -f status=running)" ]]; then
    docker start $name
fi

if [[ -z "$(docker exec -w /root/$name/docker $name bash -c 'ls build 2>/dev/null')" ]] || [[ "$base_name" == "docker_build" ]]; then
    docker exec -it -w /root/$name/docker $name bash -c 'cmake .. -B build && cd build && make -j2'
fi

if [[ "$base_name" != "docker_build" ]]; then
    threads=${1:-"1"}
    docker exec -it -w /root/$name/docker $name ./build/$base_name $threads
fi
